; concise-mid-tag code points
language = 0
tag-metadata = 1
module-metadata = 2
comid-entity = 3
linked-tags = 4
claims = 5

; claims-entry code points
ref-claims = 0
end-claims = 1
identity-claims = 2
instance-claims = 3

; corim-meta code points
signer = 98
deny-id = 99

; validity-entry code points
not-before = 100
not-after = 101

; unsigned-corim code points
corim-id = 123 ; TBD
tags = 97
dependent-rims = 122; TBD
