
; expansion of rel values to accomodate comid relationship
$rel /= m-requires
$rel /= m-runs-on

; A software module identified by this tag may require or depends on 
; one or more modules(firmwares) to be loaded or already present
m-requires = 12

; A software module identified by this tag runs on a module
; identified by the linked tag(s). The module here represent
; the exact hardware where this software is executed
m-runs-on = 13


