COSE_Key = {
  1 => tstr / int,          ; kty
  ? 2 => bstr,              ; kid
  ? 3 => tstr / int,        ; alg
  ? 4 => [+ (tstr / int) ], ; key_ops
  ? 5 => bstr,              ; Base IV
  * cose-key-label => cose-key-values
}

cose-key-label = int / tstr
cose-key-values = any

COSE_KeySet = [+COSE_Key]
