signed-corim = #6.18(COSE-Sign1-corim)

cose-label = int / tstr
cose-values = any

protected-signed-corim-header = {
  1 => int,                      ; algorithm identifier
  3 => "application/rim+cbor",   ; content type identifier
  4 => bstr,                     ; key identifier of issuer?
  corim-meta-key => corim-meta   ; corim signature attributes
  * cose-label => cose-values,
}
corim-meta-key = 8 ; scoped to protected-signed-corim-header map

corim-meta = {
  signer => entity-entry, ; entity-entry is pointing to the manifest issuer - compare tag-metadata tag-issuer these are different things
  ? validity-entry,
  ? deny-id => corim-id-type, ; used for revocation - NOTE(tho) I'm not sure I understand how is this supposed to work?
}
signer = 98
deny-id = 99

validity-entry = (
  ? not-before => time,
  not-after => time,
)
not-before=100
not-after=101

unprotected-signed-corim-header = {
  * cose-label => cose-values,
}

COSE-Sign1-corim = [
  protected: bstr .cbor protected-signed-corim-header,
  unprotected: unprotected-signed-corim-header,
  payload: bstr .cbor unsigned-corim,
  signature: bstr,
]

