$$link-extension //= (
  ? privilege => $privilege,
)

; expansion of rel values to accomodate comid relationship
$rel /= m-requires
$rel /= m-runs-on
$rel /= m-part-of
$rel /= m-supplemental
$rel /= -256..64436 / text

; A software module identified by this tag may require or depends on 
; one or more modules(firmwares) identified by the linked tag(s)
m-requires = 12
; A software module identified by this tag runs on a module
; identified by the linked tag(s)
m-runs-on = 13
; A software module identified by this tag is part of a sub-system (or module)
; to which this tag links to
m-part-of = 14

; A software module identified by this tag provides additional information
; about the module it links to
m-supplemental = 15


; privilege indicates level of privilege that is required for this SW to run
; on a given module, i.e. whether this SW runs in a 
; Trusted Execution Environment(TEE) or not?

; "privilege" integer indexes
trusted=1
untrusted=2


$privilege /= trusted
$privilege /= untrusted
$privilege /= int / text
