unsigned-corim = {
  corim-id => corim-id-type,
  tags => concise-tag / [2* concise-tag],
  ? dependent-rims => corim-locator / [2* corim-locator], ; hint for finding manifest files
  * $$unsigned-corim-extension
}
corim-id = 123 ; TBD
tags = 97
dependent-rims = 122; TBD

corim-id-type = tstr / bstr .size 16 ; **Note: Do we want a %6.CT reservation?**

corim-locator = {
  href => any-uri, ; e.g. https://isv.example.mymodule.corim
  ? thumbprint => hash-entry, ; the digest computed over mymodule.corim
  ; **Note:should there be an extension point here?**
}

concise-tag = #6.47116(signed-coswid) / #6.47117(concise-mid-tag)
; NOTE(henk) does a concise-mid-tag by itself should be allowed to be singed the same as a CoSWID tag?
